version: "3.7"

services:
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - radarr-config:/config
      - ${ROOT}/data/tv:/data
      - ${ROOT}/data/torrents:/app/qBittorrent/downloads

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - sonarr-config:/config
      - ${ROOT}/data/movies:/data
      - ${ROOT}/data/torrents:/app/qBittorrent/downloads

  prowlarr:
    container_name: prowlarr
    image: cr.hotio.dev/hotio/prowlarr:nightly
    restart: unless-stopped
    ports:
      - 9696:9696
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - prowlarr-config:/config

  qflood:
    container_name: qflood
    image: cr.hotio.dev/hotio/qflood
    restart: unless-stopped
    ports:
      - 8080:8080
      - 3000:3000
    environment:
      - FLOOD_AUTH=false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - qflood-config:/config
      - ${ROOT}/data/torrents:/app/qBittorrent/downloads

  jellyfin:
    container_name: jellyfin
    image: cr.hotio.dev/hotio/jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - jellyfin-config:/config
      - ${ROOT}/data:/data

  setup:
    build: auto-configure/.
    depends_on:
      - radarr
      - sonarr
      - prowlarr

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  qflood-config:
  jellyfin-config:
